#!/usr/bin/env bun
/**
 * LaunchdPlist.ts - Generate and install launchd plist for PublicSync
 *
 * Generates a launchd plist that runs the PublicSync workflow daily at 2am.
 *
 * Usage:
 *   bun ~/.claude/skills/System/PublicSync/Tools/LaunchdPlist.ts generate
 *   bun ~/.claude/skills/System/PublicSync/Tools/LaunchdPlist.ts install
 *   bun ~/.claude/skills/System/PublicSync/Tools/LaunchdPlist.ts uninstall
 *   bun ~/.claude/skills/System/PublicSync/Tools/LaunchdPlist.ts status
 *
 * @author Kaya System
 * @version 1.0.0
 */

import { writeFileSync, existsSync, mkdirSync } from "fs";
import { execSync } from "child_process";
import { homedir } from "os";
import { join } from "path";

const PLIST_LABEL = "com.kaya.publicsync";
const SKILL_DIR = join(homedir(), ".claude", "skills", "System", "PublicSync");
const STATE_DIR = join(SKILL_DIR, "State");
const PLIST_FILENAME = `${PLIST_LABEL}.plist`;
const PLIST_STATE_PATH = join(STATE_DIR, PLIST_FILENAME);
const LAUNCHD_AGENTS_DIR = join(homedir(), "Library", "LaunchAgents");
const LAUNCHD_PLIST_PATH = join(LAUNCHD_AGENTS_DIR, PLIST_FILENAME);

const LOG_PATH = join(homedir(), ".claude", "MEMORY", "logs", "publicsync.log");
const ERROR_LOG_PATH = join(
  homedir(),
  ".claude",
  "MEMORY",
  "logs",
  "publicsync-error.log"
);

/**
 * Generate the launchd plist XML content.
 * Runs daily at 2:00am.
 */
function generatePlistContent(): string {
  const syncScriptPath = join(SKILL_DIR, "Tools", "SyncRunner.sh");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${syncScriptPath}</string>
    </array>

    <!-- Run daily at 2:00am -->
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>2</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>

    <!-- Logging -->
    <key>StandardOutPath</key>
    <string>${LOG_PATH}</string>
    <key>StandardErrorPath</key>
    <string>${ERROR_LOG_PATH}</string>

    <!-- Run even if the system was sleeping at the scheduled time -->
    <key>RunAtLoad</key>
    <false/>

    <!-- Environment for bun -->
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin</string>
        <key>HOME</key>
        <string>${homedir()}</string>
    </dict>
</dict>
</plist>
`;
}

/**
 * Generate the shell runner script that launchd executes.
 * Uses bun to run the sync engine.
 */
function generateRunnerScript(): string {
  const syncEnginePath = join(SKILL_DIR, "Tools", "SyncRunner.ts");
  return `#!/bin/bash
# PublicSync daily runner
# Generated by LaunchdPlist.ts
# Runs at 2:00am daily via launchd

set -euo pipefail

BUN=$(which bun 2>/dev/null || echo "/opt/homebrew/bin/bun")
SYNC_ENGINE="${syncEnginePath}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] PublicSync starting..."

if [ ! -f "$SYNC_ENGINE" ]; then
  echo "[ERROR] SyncRunner not found at $SYNC_ENGINE" >&2
  exit 1
fi

"$BUN" "$SYNC_ENGINE" --auto

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] PublicSync complete."
`;
}

// ─────────────────────────────────────────────────────────────
// Commands
// ─────────────────────────────────────────────────────────────

function generate(): void {
  console.log("[LaunchdPlist] Generating plist and runner script...");

  mkdirSync(STATE_DIR, { recursive: true });

  const plistContent = generatePlistContent();
  writeFileSync(PLIST_STATE_PATH, plistContent);
  console.log(`  Written: ${PLIST_STATE_PATH}`);

  const runnerPath = join(SKILL_DIR, "Tools", "SyncRunner.sh");
  writeFileSync(runnerPath, generateRunnerScript(), { mode: 0o755 });
  console.log(`  Written: ${runnerPath}`);

  console.log("[LaunchdPlist] Done. Run 'install' to activate.");
}

function install(): void {
  if (!existsSync(PLIST_STATE_PATH)) {
    generate();
  }

  mkdirSync(LAUNCHD_AGENTS_DIR, { recursive: true });

  // Copy plist to LaunchAgents
  execSync(`cp "${PLIST_STATE_PATH}" "${LAUNCHD_PLIST_PATH}"`);
  console.log(`[LaunchdPlist] Installed: ${LAUNCHD_PLIST_PATH}`);

  // Load the agent
  try {
    execSync(`launchctl load "${LAUNCHD_PLIST_PATH}"`, { stdio: "pipe" });
    console.log("[LaunchdPlist] Loaded with launchctl.");
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    console.warn("[LaunchdPlist] launchctl load warning:", message);
  }

  status();
}

function uninstall(): void {
  if (existsSync(LAUNCHD_PLIST_PATH)) {
    try {
      execSync(`launchctl unload "${LAUNCHD_PLIST_PATH}"`, { stdio: "pipe" });
      console.log("[LaunchdPlist] Unloaded from launchctl.");
    } catch {
      // May already be unloaded
    }
    execSync(`rm "${LAUNCHD_PLIST_PATH}"`);
    console.log(`[LaunchdPlist] Removed: ${LAUNCHD_PLIST_PATH}`);
  } else {
    console.log("[LaunchdPlist] Not installed.");
  }
}

function status(): void {
  console.log("\n[LaunchdPlist] Status:");
  console.log(
    `  Plist in State:      ${existsSync(PLIST_STATE_PATH) ? "EXISTS" : "MISSING"}`
  );
  console.log(
    `  Plist in LaunchAgents: ${existsSync(LAUNCHD_PLIST_PATH) ? "INSTALLED" : "NOT INSTALLED"}`
  );

  if (existsSync(LAUNCHD_PLIST_PATH)) {
    try {
      const result = execSync(`launchctl list | grep "${PLIST_LABEL}"`, {
        stdio: "pipe",
      }).toString();
      console.log(`  launchd status:      ${result.trim() || "not loaded"}`);
    } catch {
      console.log("  launchd status:      not loaded");
    }
  }
}

// ─────────────────────────────────────────────────────────────
// CLI
// ─────────────────────────────────────────────────────────────

if (import.meta.main) {
  const cmd = process.argv[2] ?? "help";

  switch (cmd) {
    case "generate":
      generate();
      break;
    case "install":
      install();
      break;
    case "uninstall":
      uninstall();
      break;
    case "status":
      status();
      break;
    default:
      console.log(`
PublicSync LaunchdPlist Tool

USAGE:
  bun LaunchdPlist.ts <command>

COMMANDS:
  generate    Generate plist file to State/ and runner script
  install     Install and activate the daily 2am sync job
  uninstall   Remove and deactivate the sync job
  status      Show current installation status

PLIST LABEL: ${PLIST_LABEL}
SCHEDULE:    Daily at 2:00am
`);
  }
}
