#!/bin/bash
# PublicSync daily runner
# Generated by LaunchdPlist.ts
# Runs at 2:00am daily via launchd

set -euo pipefail

BUN=$(which bun 2>/dev/null || echo "/opt/homebrew/bin/bun")
SYNC_ENGINE="~/.claude/skills/System/PublicSync/Tools/SyncRunner.ts"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] PublicSync starting..."

if [ ! -f "$SYNC_ENGINE" ]; then
  echo "[ERROR] SyncRunner not found at $SYNC_ENGINE" >&2
  exit 1
fi

"$BUN" "$SYNC_ENGINE" --auto

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] PublicSync complete."
