#!/usr/bin/env bun
/**
 * SyncEngine - Generic context file writer for InformationManager
 *
 * A generic execution engine that:
 * - Accepts source config as parameters (NOT hardcoded)
 * - Writes context files with standard frontmatter
 * - Handles notifications
 * - Has NO source-specific logic
 *
 * Usage:
 *   bun run SyncEngine.ts --source lucidtasks --title "LucidTasks" --output context/LucidTasksContext.md --content "..."
 *   echo '{"source":"test","title":"Test","outputPath":"test.md","content":"# Test"}' | bun SyncEngine.ts --stdin
 *
 * Options:
 *   --source <name>        Source identifier (lucidtasks, calendar, etc.)
 *   --title <title>        Title for the context file
 *   --output <path>        Output file path (relative to KAYA_DIR or absolute)
 *   --content <content>    Content to write (or use --stdin)
 *   --entries <count>      Optional entry count metric
 *   --stdin                Read SyncConfig JSON from stdin
 *   --notify               Send notification on completion
 *   --dry-run              Preview without writing
 *   --json                 Output result as JSON
 *   --help                 Show this help
 */

import { parseArgs } from "util";
import * as fs from "fs";
import * as path from "path";

// ============================================================================
// Configuration
// ============================================================================

const HOME = process.env.HOME || "/Users/[user]";
const KAYA_DIR = process.env.KAYA_DIR || path.join(HOME, ".claude");

// ============================================================================
// Types
// ============================================================================

export interface SyncConfig {
  source: string;           // "lucidtasks", "calendar", etc.
  title: string;            // "LucidTasks Context"
  outputPath: string;       // Full path or relative to KAYA_DIR
  content: string;          // The context content to write
  entriesCount?: number;    // Optional metric
}

export interface SyncResult {
  success: boolean;
  source: string;
  outputPath: string;
  entriesCount?: number;
  timestamp: string;
  error?: string;
  durationMs: number;
}

// ============================================================================
// Core Functions
// ============================================================================

function resolveOutputPath(outputPath: string): string {
  if (path.isAbsolute(outputPath)) {
    return outputPath;
  }
  return path.join(KAYA_DIR, outputPath);
}

function generateFrontmatter(config: SyncConfig, timestamp: string): string {
  const tags = ["context", "ai-context", config.source];

  let frontmatter = `---
tags: [${tags.join(", ")}]
last_updated: ${timestamp}
gathered_by: InformationManager
`;

  if (config.entriesCount !== undefined) {
    frontmatter += `entries_count: ${config.entriesCount}\n`;
  }

  frontmatter += `---\n`;
  return frontmatter;
}

export async function syncToContext(config: SyncConfig): Promise<SyncResult> {
  const startTime = Date.now();
  const timestamp = new Date().toISOString();
  const resolvedPath = resolveOutputPath(config.outputPath);

  try {
    // Validate config
    if (!config.source) {
      throw new Error("Missing required field: source");
    }
    if (!config.title) {
      throw new Error("Missing required field: title");
    }
    if (!config.outputPath) {
      throw new Error("Missing required field: outputPath");
    }
    if (config.content === undefined) {
      throw new Error("Missing required field: content");
    }

    // Ensure output directory exists
    const outputDir = path.dirname(resolvedPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Generate file content with frontmatter
    const frontmatter = generateFrontmatter(config, timestamp);
    const fileContent = `${frontmatter}
# ${config.title}

${config.content}

---
*Generated by InformationManager/Tools/SyncEngine.ts*
`;

    // Write file
    fs.writeFileSync(resolvedPath, fileContent);

    return {
      success: true,
      source: config.source,
      outputPath: resolvedPath,
      entriesCount: config.entriesCount,
      timestamp,
      durationMs: Date.now() - startTime,
    };
  } catch (error) {
    return {
      success: false,
      source: config.source,
      outputPath: resolvedPath,
      timestamp,
      error: error instanceof Error ? error.message : String(error),
      durationMs: Date.now() - startTime,
    };
  }
}

async function sendNotification(message: string): Promise<void> {
  try {
    const { notifyAsync } = await import("../../../../lib/core/NotificationService");
    await notifyAsync(message, "InformationManager");
  } catch {
    // Notification server not running - silent fail
  }
}

// ============================================================================
// CLI
// ============================================================================

async function main() {
  const { values } = parseArgs({
    args: Bun.argv.slice(2),
    options: {
      source: { type: "string", short: "s" },
      title: { type: "string", short: "t" },
      output: { type: "string", short: "o" },
      content: { type: "string", short: "c" },
      entries: { type: "string", short: "e" },
      stdin: { type: "boolean" },
      notify: { type: "boolean", short: "n" },
      "dry-run": { type: "boolean" },
      json: { type: "boolean" },
      help: { type: "boolean", short: "h" },
    },
  });

  if (values.help) {
    console.log(`
SyncEngine - Generic context file writer for InformationManager

Usage:
  bun run SyncEngine.ts --source lucidtasks --title "LucidTasks" --output context/LucidTasksContext.md --content "..."
  echo '{"source":"test",...}' | bun SyncEngine.ts --stdin

Options:
  --source <name>        Source identifier (lucidtasks, calendar, etc.)
  --title <title>        Title for the context file
  --output <path>        Output file path (relative to KAYA_DIR or absolute)
  --content <content>    Content to write (or use --stdin)
  --entries <count>      Optional entry count metric
  --stdin                Read SyncConfig JSON from stdin
  --notify               Send notification on completion
  --dry-run              Preview without writing
  --json                 Output result as JSON
  --help                 Show this help

SyncConfig JSON format:
{
  "source": "lucidtasks",
  "title": "LucidTasks Context",
  "outputPath": "context/LucidTasksContext.md",
  "content": "## Tasks\\n- Task 1\\n- Task 2",
  "entriesCount": 2
}
`);
    process.exit(0);
  }

  let config: SyncConfig;

  if (values.stdin) {
    // Read config from stdin
    const stdinContent = await Bun.stdin.text();
    try {
      config = JSON.parse(stdinContent.trim());
    } catch {
      console.error("Error: Invalid JSON on stdin");
      process.exit(1);
    }
  } else {
    // Build config from CLI args
    if (!values.source || !values.title || !values.output || !values.content) {
      console.error("Error: Required fields: --source, --title, --output, --content (or use --stdin)");
      process.exit(1);
    }

    config = {
      source: values.source,
      title: values.title,
      outputPath: values.output,
      content: values.content,
      entriesCount: values.entries ? parseInt(values.entries) : undefined,
    };
  }

  if (values["dry-run"]) {
    console.log("=== Dry Run ===");
    console.log(`Source: ${config.source}`);
    console.log(`Title: ${config.title}`);
    console.log(`Output: ${resolveOutputPath(config.outputPath)}`);
    console.log(`Entries: ${config.entriesCount ?? "N/A"}`);
    console.log(`Content length: ${config.content.length} chars`);
    process.exit(0);
  }

  const result = await syncToContext(config);

  if (values.notify) {
    const message = result.success
      ? `Synced ${config.source} context (${config.entriesCount ?? 0} entries)`
      : `Failed to sync ${config.source}: ${result.error}`;
    await sendNotification(message);
  }

  if (values.json) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    if (result.success) {
      console.log(`[OK] ${result.source}: Written to ${result.outputPath} (${result.durationMs}ms)`);
      if (result.entriesCount) {
        console.log(`     Entries: ${result.entriesCount}`);
      }
    } else {
      console.log(`[FAIL] ${result.source}: ${result.error}`);
    }
  }

  process.exit(result.success ? 0 : 1);
}

// Run if executed directly
if (import.meta.main) {
  main().catch(console.error);
}
